name: wallet_watchers_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  fl_chart: ^0.63.0
  image_picker: ^1.0.4
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_smart_reply: ^0.13.0
  shared_preferences: ^2.0.15
  webview_flutter: ^4.2.2
  cupertino_icons: ^1.0.2
  uuid: ^4.0.0
  table_calendar: ^3.0.9
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.5

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/app_logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo/app_logo.png
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/logo/app_logo.png
